import Link from "next/link";
import React from "react";
import { dashboardTokens, type DashboardTone } from "@/lib/design-system";
import { StatusBadge } from "./StatusBadge"; export type AlertPriority = "critical" | "important" | "low"; export type DashboardAlert = { id: string; priority: AlertPriority; title: string; description: string; actionLabel: string; href: string;
}; const priorityMeta: Record< AlertPriority, { label: string; tone: DashboardTone; border: string }
> = { critical: { label: "Critical", tone: "critical", border: "border-l-rose-500", }, important: { label: "Important", tone: "important", border: "border-l-amber-500", }, low: { label: "Low", tone: "neutral", border: "border-l-zinc-300 dark:border-l-zinc-700", },
}; type AlertCenterProps = { alerts: DashboardAlert[]; maxVisible?: number;
}; export function AlertCenter({ alerts, maxVisible = 3 }: AlertCenterProps) { const visibleAlerts = alerts.slice(0, maxVisible); const hiddenCount = Math.max(alerts.length - visibleAlerts.length, 0); if (alerts.length === 0) { return ( <div className="rounded-xl border border-data-positive bg-data-positive p-5 "> <StatusBadge tone="success">Stable</StatusBadge> <h2 className="mt-3 text-base font-semibold text-data-positive "> All priority systems are clear </h2> <p className="mt-1 text-sm text-data-positive "> No critical or important items need action right now. </p> </div> ); } return ( <div className="flex flex-col gap-3"> {visibleAlerts.map((alert) => { const meta = priorityMeta[alert.priority]; return ( <div key={alert.id} className={`rounded-xl border-y border-r border-l-4 border-border bg-card p-4 shadow-sm ${meta.border}`} > <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"> <div className="min-w-0"> <StatusBadge tone={meta.tone}>{meta.label}</StatusBadge> <h3 className="mt-3 text-sm font-semibold text-zinc-950 "> {alert.title} </h3> <p className={`mt-1 ${dashboardTokens.text.muted}`}>{alert.description}</p> </div> <Link href={alert.href} className="inline-flex shrink-0 items-center justify-center rounded-lg bg-zinc-950 px-3 py-2 text-sm font-medium text-white transition-colors hover:bg-muted dark:bg-card dark:hover:bg-zinc-200" > {alert.actionLabel} </Link> </div> </div> ); })} {hiddenCount > 0 && ( <p className="px-1 text-sm text-muted-foreground"> {hiddenCount} lower-priority item{hiddenCount === 1 ? "" : "s"} grouped to keep today focused. </p> )} </div> );
}
